services:
  # Development services
  frontend-dev:
    container_name: textfsm-editor-frontend-dev
    build:
      context: frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "${FRONTEND_PORT_DEV:-5173}:5173"
    environment:
      - VITE_API_ENTRYPOINT_DEV=${VITE_API_ENTRYPOINT_DEV:-http://localhost:8000}
    stdin_open: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend-dev
    profiles:
      - dev

  backend-dev:
    container_name: textfsm-editor-backend-dev
    build:
      context: backend
      dockerfile: Dockerfile
      target: development
    ports:
      - "${BACKEND_PORT_DEV:-8000}:8000"
    volumes:
      - ./backend/src:/app/src
    profiles:
      - dev

