[project]
name = "textfsm-editor-backend"
version = "0.1.0"
description = "Add a short description here"
authors = [
    { name = "yuyosy", email = "y-ysss@outlook.com" }
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.0",
    "textfsm>=1.1.3",
]
